apiVersion: v1
kind: Pod
metadata:
  name: fastapi-app
  labels:
    app: fastapi
spec:
  containers:
  - name: fastapi-container
    image: mohamedaminechihi/fastapi-app:0.1.0
#    resources:
#      limits:
#        memory: "128Mi"
#        cpu: "500m"
    ports:
      - containerPort: 8000
