name: Docker Image CI

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . t -mohamedaminechihi/fastapi-app:latest
    - name: publish
      run: |
        docker login -u mohamedaminechihi -p ${{ secrets.GITHUB_TOKEN }}
        docker push mohamedaminechihi/fastapi-app:latest
