name: Publish image to Docker Hub
on:
  push:
    branches: ['main']
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: | 
          docker build . -t mohamedaminechihi/fastapi-app:latest
      - name: publish
        run: | 
          docker login -u mohamedaminechihi -p ${{ secrets:DOCKER_HUB_TOKEN  }}
          docker push mohamedaminechihi/fastapi-app:latest
                        
